version: '3'

services:
  banking-service-app:
    image: 'banking-service-h2m:latest'
    ports:
      - "8082:8080"
    build:
      context: .
    container_name: banking-service
    environment:
      SPRING_PROFILES_ACTIVE: local