version: '3'

services:
  banking-service-app:
    image: 'banking-service-mysql:latest'
    restart: always
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: banking-service
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      SPRING_PROFILES_ACTIVE: prod

  mysqldb:
    container_name: mysql
    image: mysql
    volumes:
      - /Users/apple/Desktop/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: bankingDB
      MYSQL_ROOT_PASSWORD: root